---
abstract: "RJRAY's favorite modules"
author:
  - 'Randy J. Ray <rjray@blackperl.com>'
build_requires:
  Module::Build: 0.28
  Test::More: 0.80
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-RJRAY
provides:
  Task::BeLike::RJRAY:
    file: lib/Task/BeLike/RJRAY.pm
    version: 0.001
requires:
  perl: 5.008008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Task-BeLike-RJRAY
  homepage: http://search.cpan.org/dist/Task-BeLike-RJRAY
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rjray/task-belike-rjray
version: 0.002
